-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
ROLLBACK;

BEGIN;

DROP TABLE IF EXISTS public."Violation" CASCADE;
DROP TABLE IF EXISTS public."Goal" CASCADE;
DROP TABLE IF EXISTS public."Results" CASCADE;
DROP TABLE IF EXISTS public."Team_player" CASCADE;
DROP TABLE IF EXISTS public."Game_team" CASCADE;
DROP TABLE IF EXISTS public."Match" CASCADE;
DROP TABLE IF EXISTS public."Bracket" CASCADE;
DROP TABLE IF EXISTS public."Team" CASCADE;
DROP TABLE IF EXISTS public."Club" CASCADE;
DROP TABLE IF EXISTS public."Players" CASCADE;
DROP TABLE IF EXISTS public."Country" CASCADE;

CREATE TABLE IF NOT EXISTS public."Players"
(
    player_id serial NOT NULL,
    surname character varying(50) NOT NULL,
    name character varying(50) NOT NULL,
    patronymic character varying(50),
    country_id integer NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (player_id),
	CONSTRAINT check_birth_date CHECK (birth_date >= '1900-01-01'::date AND birth_date <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS public."Country"
(
    id_country serial,
    short_name character varying(3) NOT NULL,
    long_name character varying(100) NOT NULL,
    region character varying(50) NOT NULL,
    PRIMARY KEY (id_country),
    CONSTRAINT sh_name UNIQUE (short_name),
    CONSTRAINT l_name UNIQUE (long_name),
	CONSTRAINT check_region CHECK (region IN (
        'Европа', 
        'Азия', 
        'Африка', 
        'Северная Америка', 
        'Южная Америка', 
        'Латинская Америка',
        'Австралия и Океания'
    ))
);

CREATE TABLE IF NOT EXISTS public."Club"
(
    club_id serial,
    short_name character varying(50) NOT NULL,
    long_name character varying(100) NOT NULL,
    PRIMARY KEY (club_id),
    CONSTRAINT club_l_name UNIQUE (long_name)
);

CREATE TABLE IF NOT EXISTS public."Team"
(
    team_id serial,
    team_name character varying(50) NOT NULL,
    country_id integer,
    club_id integer,
    PRIMARY KEY (team_id),
    CONSTRAINT team_name_team UNIQUE (team_name),
	CONSTRAINT check_team_affiliation CHECK (
        (country_id IS NOT NULL AND club_id IS NULL) OR 
        (country_id IS NULL AND club_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public."Team_player"
(
    id serial,
    player_id integer NOT NULL,
    "number" integer NOT NULL,
    game_team_id integer NOT NULL,
    "position" character varying NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT name_team UNIQUE (game_team_id, "number"),
	CONSTRAINT check_player_number CHECK ("number" > 0 AND "number" < 100),
    CONSTRAINT check_position CHECK ("position" IN (
        'Forward', 'Midfielder', 'Defender', 'Goalkeeper',
        'Нападающий', 'Полузащитник', 'Защитник', 'Вратарь'
    ))
);

CREATE TABLE IF NOT EXISTS public."Bracket"
(
    id serial,
    round_name character varying(50) NOT NULL,
    parent_bracket_id integer,
    PRIMARY KEY (id),
    UNIQUE (round_name),
	CONSTRAINT check_round_name CHECK (round_name IN (
		'Группа A', 'Группа B', 'Группа C', 'Группа D',
		'1/8 финала', '1/4 финала', 'Полуфинал', 'Финал', 'Матч за 3 место'
	))
);

CREATE TABLE IF NOT EXISTS public."Match"
(
    id_match serial,
    bracket_id integer NOT NULL,
    location character varying(50) NOT NULL,
    match_date date NOT NULL,
    match_time time without time zone NOT NULL,
    PRIMARY KEY (id_match),
	UNIQUE (location, match_date, match_time),
	CONSTRAINT check_future_match CHECK (match_date >= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS public."Game_team"
(
    game_team_id serial,
    match_id integer NOT NULL,
    team_id integer NOT NULL,
    is_home boolean NOT NULL,
    PRIMARY KEY (game_team_id),
    UNIQUE (match_id, is_home),
    UNIQUE (match_id, team_id)
);

CREATE TABLE IF NOT EXISTS public."Goal"
(
    goal_id serial,
    team_player_id integer NOT NULL,
    minute integer NOT NULL,
    PRIMARY KEY (goal_id),
	CONSTRAINT check_goal_minute CHECK ("minute" >= 0 AND "minute" <= 120)
);

CREATE TABLE IF NOT EXISTS public."Violation"
(
    violation_id serial,
    minute integer NOT NULL,
    team_player_id integer NOT NULL,
    card_type character varying NOT NULL,
    PRIMARY KEY (violation_id),
	CONSTRAINT check_violation_minute CHECK ("minute" >= 0 AND "minute" <= 120),
    CONSTRAINT check_card_type CHECK (card_type IN ('Yellow', 'Red', 'Green'))
	
);

CREATE TABLE IF NOT EXISTS public."Results"
(
    result_id serial NOT NULL,
    game_team_id integer NOT NULL,
    score integer NOT NULL DEFAULT 0,
    penalties integer,
    points integer,
    PRIMARY KEY (result_id),
    UNIQUE (game_team_id),
	CONSTRAINT check_result_score CHECK (score >= 0),
	CONSTRAINT check_penalties CHECK (penalties >= 0),
    CONSTRAINT check_points CHECK (points >= 0)
);


ALTER TABLE IF EXISTS public."Players"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."Country" (id_country) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Team"
    ADD FOREIGN KEY (club_id)
    REFERENCES public."Club" (club_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public."Team"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."Country" (id_country) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public."Match"
    ADD FOREIGN KEY (bracket_id)
    REFERENCES public."Bracket" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Game_team"
    ADD FOREIGN KEY (match_id)
    REFERENCES public."Match" (id_match) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE; -- Если удалили матч, удаляются и записи о командах в нем

ALTER TABLE IF EXISTS public."Game_team"
    ADD FOREIGN KEY (team_id)
    REFERENCES public."Team" (team_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Team_player"
    ADD FOREIGN KEY (player_id)
    REFERENCES public."Players" (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Team_player"
    ADD FOREIGN KEY (game_team_id)
    REFERENCES public."Game_team" (game_team_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."Goal"
    ADD FOREIGN KEY (team_player_id)
    REFERENCES public."Team_player" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."Violation"
    ADD FOREIGN KEY (team_player_id)
    REFERENCES public."Team_player" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."Results"
    ADD FOREIGN KEY (game_team_id)
    REFERENCES public."Game_team" (game_team_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMIT;


BEGIN;

INSERT INTO "Country" (short_name, long_name, region) VALUES
('RUS', 'Россия', 'Европа'),
('ENG', 'Англия', 'Европа'),
('ESP', 'Испания', 'Европа'),
('GER', 'Германия', 'Европа'),
('BRA', 'Бразилия', 'Южная Америка'),
('ARG', 'Аргентина', 'Южная Америка');

INSERT INTO "Club" (short_name, long_name) VALUES
('Спартак', 'Спартак-Москва'),
('Реал', 'Реал Мадрид'),
('Барса', 'ФК Барселона'),
('Бавария', 'Бавария Мюнхен'),
('МЮ', 'Манчестер Юнайтед'),
('ПСЖ', 'Пари Сен-Жермен');


INSERT INTO "Players" (surname, name, patronymic, country_id, birth_date) VALUES
('Соболев', 'Александр', 'Сергеевич', 1, '1997-04-07'),
('Кейн', 'Гарри', 'Джеймс', 2, '1993-07-28'),
('Мюллер', 'Томас', NULL, 4, '1989-09-13'),
('Пике', 'Жерар', NULL, 3, '1987-02-02'),
('Неймар', 'да Силва', 'Сантос Жуниор', 5, '1992-02-05'),
('Месси', 'Лионель', 'Андрес', 6, '1987-06-24');

INSERT INTO "Team" (team_name, country_id, club_id) VALUES
('Сборная России', 1, NULL),
('Сборная Англии', 2, NULL),
('Сборная Испании', 3, NULL),
('Сборная Германии', 4, NULL),
('Сборная Бразилии', 5, NULL),
('Сборная Аргентины', 6, NULL),
('Спартак-Москва', NULL, 1),
('Реал Мадрид', NULL, 2),
('Барселона', NULL, 3),
('Бавария Мюнхен', NULL, 4),
('Манчестер Юнайтед', NULL, 5);

INSERT INTO "Bracket" (round_name, parent_bracket_id) VALUES
('Группа A', NULL),
('Группа B', NULL),
('1/4 финала', NULL),
('Полуфинал', NULL),
('Финал', NULL),
('Матч за 3 место', NULL);


INSERT INTO "Match" (bracket_id, location, match_date, match_time) VALUES
(1, 'Москва, Лужники', '2027-06-01', '18:00:00'),
(1, 'Лондон, Уэмбли', '2027-06-02', '20:00:00'),
(3, 'Мадрид, Бернабеу', '2027-06-10', '19:00:00'),
(4, 'Берлин, Олимпиаштадион', '2027-06-15', '21:00:00'),
(5, 'Париж, Сен-Дени', '2027-06-20', '20:00:00'),
(6, 'Рим, Олимпико', '2027-06-18', '18:00:00');


INSERT INTO "Game_team" (match_id, team_id, is_home) VALUES
(1, 1, TRUE), (1, 2, FALSE),
(2, 3, TRUE), (2, 4, FALSE),
(3, 7, TRUE), (3, 8, FALSE),
(4, 2, TRUE), (4, 5, FALSE),
(5, 3, TRUE), (5, 4, FALSE),
(6, 5, TRUE), (6, 6, FALSE);


INSERT INTO "Team_player" (player_id, "number", game_team_id, "position") VALUES
(1, 9, 1, 'Нападающий'),
(2, 10, 2, 'Forward'),
(4, 3, 3, 'Defender'),
(3, 25, 4, 'Midfielder'),
(1, 8, 5, 'Полузащитник'),
(2, 7, 6, 'Forward'),
(2, 9, 7, 'Forward'),
(5, 10, 8, 'Нападающий'),
(4, 4, 9, 'Защитник'),
(3, 13, 10, 'Midfielder'),
(5, 11, 11, 'Forward'),
(6, 11, 12, 'Полузащитник');


INSERT INTO "Goal" (team_player_id, "minute") VALUES
(1, 23), (2, 67), (3, 12), (4, 45), (3, 89), (5, 34);

INSERT INTO "Violation" ("minute", team_player_id, card_type) VALUES
(30, 1, 'Yellow'),
(55, 2, 'Yellow'),
(72, 4, 'Red'),
(88, 5, 'Yellow'),
(90, 3, 'Green');


INSERT INTO "Results" (game_team_id, score, points) VALUES
(1, 2, 3), (2, 1, 0),
(3, 3, 3), (4, 2, 0),
(5, 1, 0), (6, 2, 3),
(7, 1, 1), (8, 1, 1),
(9, 2, 3), (10, 1, 0),
(11, 2, 1), (12, 2, 1);

COMMIT;

--Список всех игроков с названием их стран
SELECT p.surname, p.name, c.long_name  FROM "Players" p
JOIN "Country" c ON p.country_id = c.id_country;

--Cостав на конкретный матч
SELECT t.team_name, tp."number", tp."position", 
       p.surname, p.name
FROM "Team_player" tp
JOIN "Game_team" gt ON tp.game_team_id = gt.game_team_id
JOIN "Team" t ON gt.team_id = t.team_id
JOIN "Players" p ON tp.player_id = p.player_id
WHERE gt.match_id = 1
ORDER BY t.team_name, tp."position";

--Количество голов, забитых в каждом тайме
SELECT 
    CASE 
        WHEN "minute" <= 45 THEN '1-й тайм'
        WHEN "minute" <= 90 THEN '2-й тайм'
        ELSE 'Дополнительное время'
    END AS match_period,
    COUNT(*) AS goals_count
FROM "Goal"
GROUP BY match_period
ORDER BY MIN("minute");

--Игроки, которые ни разу не получали карточки
SELECT p.surname, p.name  FROM "Players" p
WHERE p.player_id NOT IN 
				(SELECT DISTINCT tp.player_id FROM "Team_player" tp 
				 JOIN "Violation" v ON tp.id =v.team_player_id
                );
				
--Матчи, в которых было забито больше всего голов.
SELECT m.id_match, m.location, m.match_date, 
       SUM(r.score) AS total_match_goals
FROM "Match" m
JOIN "Game_team" gt ON m.id_match = gt.match_id
JOIN "Results" r ON gt.game_team_id = r.game_team_id
GROUP BY m.id_match, m.location, m.match_date
ORDER BY total_match_goals DESC
LIMIT 3;

--суммарное количество голов, забитых каждым игроком.
SELECT p.surname, COUNT(g.goal_id) AS count_goals
FROM "Players" p
JOIN "Team_player" tp ON p.player_id = tp.player_id
LEFT JOIN "Goal" g ON tp.id = g.team_player_id
GROUP BY p.player_id, p.surname
ORDER BY count_goals DESC;

--Cреднее число нарушений в матче (среднее число карточек по всем матчам).
SELECT ROUND(AVG(violation_count), 2) AS average_number_of_cards_per_match
FROM (
    SELECT m.id_match, COUNT(v.violation_id) AS violation_count
    FROM "Match" m
    JOIN "Game_team" gt ON m.id_match = gt.match_id
    JOIN "Team_player" tp ON gt.game_team_id = tp.game_team_id
    LEFT JOIN "Violation" v ON tp.id = v.team_player_id
    GROUP BY m.id_match
) AS match_violations;

--Команды, которые выиграли матч, но не забили ни одного гола
SELECT t.team_name, r.score
FROM "Team" t
JOIN "Game_team" gt ON t.team_id = gt.team_id
JOIN "Results" r ON gt.game_team_id = r.game_team_id
WHERE r.points = 3 
  AND r.score = 0;

--Стадионы, которые приняли более одного матча
SELECT location, COUNT(id_match) AS matches_hosted
FROM "Match"
GROUP BY location
HAVING COUNT(id_match) > 1;

--Возраст игроков на день первого матча их команды.
SELECT pl.surname, pl.name, t.team_name, 
       m.match_date,
       EXTRACT(YEAR FROM AGE(m.match_date, pl.birth_date)) AS age_at_match
FROM "Players" pl
JOIN "Team_player" tp ON pl.player_id = tp.player_id
JOIN "Game_team" gt ON tp.game_team_id = gt.game_team_id
JOIN "Match" m ON gt.match_id = m.id_match
JOIN "Team" t ON gt.team_id = t.team_id
WHERE m.match_date = (
    SELECT MIN(m2.match_date) 
    FROM "Match" m2 
    JOIN "Game_team" gt2 ON m2.id_match = gt2.match_id 
    WHERE gt2.team_id = t.team_id
)
ORDER BY age_at_match DESC;

-- Рейтинг игроков по количеству голов внутри их позиции
SELECT tp."position", pl.surname, pl.name, COUNT(g.goal_id) AS goals,
       RANK() OVER(PARTITION BY tp."position" ORDER BY COUNT(g.goal_id) DESC) AS pos_rank
FROM "Team_player" tp
JOIN "Players" pl ON tp.player_id = pl.player_id
LEFT JOIN "Goal" g ON tp.id = g.team_player_id
GROUP BY tp."position", pl.player_id, pl.surname, pl.name
ORDER BY tp."position", pos_rank;

--Игроки, которые играли на разных позициях в разных матчах
SELECT pl.surname, pl.name, COUNT(DISTINCT tp."position") AS positions_played
FROM "Players" pl
JOIN "Team_player" tp ON pl.player_id = tp.player_id
GROUP BY pl.player_id, pl.surname, pl.name
HAVING COUNT(DISTINCT tp."position") > 1;

--Команды, которые ни разу не играли дома
SELECT t.team_name
FROM "Team" t
WHERE NOT EXISTS (
    SELECT 1 FROM "Game_team" gt 
    WHERE gt.team_id = t.team_id AND gt.is_home = TRUE
)
AND EXISTS (
    SELECT 1 FROM "Game_team" gt 
    WHERE gt.team_id = t.team_id
);
  
--Cамый результативный по голам и самый результативный по нарушениям матчи.
WITH match_stats AS (
    SELECT m.id_match, m.location, m.match_date,
        COUNT(DISTINCT g.goal_id) AS goal_count,
        COUNT(DISTINCT v.violation_id) AS violation_count
    FROM "Match" m
    JOIN "Game_team" gt ON m.id_match = gt.match_id
    JOIN "Team_player" tp ON gt.game_team_id = tp.game_team_id
    LEFT JOIN "Goal" g ON tp.id = g.team_player_id
    LEFT JOIN "Violation" v ON tp.id = v.team_player_id
    GROUP BY m.id_match, m.location, m.match_date
)
SELECT 
    'Самый результативный по голам' AS statistic_type,
    id_match,
    location,
    match_date,
    goal_count AS value
FROM match_stats
WHERE goal_count = (SELECT MAX(goal_count) FROM match_stats)

UNION ALL

SELECT 
    'Самый результативный по нарушениям' AS statistic_type,
    id_match,
    location,
    match_date,
    violation_count AS value
FROM match_stats
WHERE violation_count = (SELECT MAX(violation_count) FROM match_stats);

--Замена названия всех клубов, дописав спереди фразу «Футбольный клуб»
UPDATE public."Club"
SET long_name = 'Футбольный клуб' || long_name;
	
SELECT * FROM "Club";







